spring:
  profiles:
    active: local
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: H2

logging:
  level:
    org:
      hibernate:
        type: trace